version: "3.8"
services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      REACT_APP_SERVER_URI: http://localhost:8000
