version: "3.8"
services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      REACT_APP_SERVER_URI: salon-xpert-backend.ap-southeast-1.elasticbeanstalk.com:8000
